# Generated by Django 6.0.1 on 2026-01-08 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_weight_grams', models.FloatField(default=0)),
                ('weight_sensor_online', models.BooleanField(default=False)),
                ('last_weight_reading', models.DateTimeField(blank=True, null=True)),
                ('pir_sensor_online', models.BooleanField(default=False)),
                ('bird_present', models.BooleanField(default=False)),
                ('last_pir_trigger', models.DateTimeField(blank=True, null=True)),
                ('camera_online', models.BooleanField(default=False)),
                ('last_photo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sensor Status',
            },
        ),
        migrations.CreateModel(
            name='PIREvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('cleared', 'Cleared')], max_length=10)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Dauer der Bewegung', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'event_type'], name='sensors_pir_timesta_4b5a2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeightMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('weight_grams', models.FloatField(help_text='Gewicht in Gramm')),
                ('tare_offset', models.FloatField(default=0, help_text='Tara-Offset für Kalibrierung')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='sensors_wei_timesta_c43ec7_idx')],
            },
        ),
    ]
