# Generated by Django 6.0.1 on 2026-01-08 20:18

import django.utils.timezone
import media_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaStorageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usb_total_bytes', models.BigIntegerField(default=0)),
                ('usb_used_bytes', models.BigIntegerField(default=0)),
                ('usb_available_bytes', models.BigIntegerField(default=0)),
                ('total_photos', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('photos_size_bytes', models.BigIntegerField(default=0)),
                ('videos_size_bytes', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Media Storage Stats',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('file', models.ImageField(blank=True, null=True, upload_to=media_manager.models.photo_upload_path)),
                ('usb_path', models.CharField(blank=True, help_text='Pfad auf USB Stick', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('filesize_bytes', models.BigIntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('is_thumbnail_generated', models.BooleanField(default=False)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='media_manag_timesta_a00bc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to=media_manager.models.video_upload_path)),
                ('usb_path', models.CharField(blank=True, help_text='Pfad auf USB Stick', max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('filesize_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('framerate', models.IntegerField(default=30)),
                ('codec', models.CharField(default='h264', max_length=50)),
                ('thumbnail_frame', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='media_manag_timesta_e6555c_idx')],
            },
        ),
    ]
