# Generated by Django 6.0.1 on 2026-01-08 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('common_name_de', models.CharField(blank=True, max_length=200)),
                ('common_name_en', models.CharField(blank=True, max_length=200)),
                ('inat_taxon_id', models.IntegerField(blank=True, help_text='iNaturalist Taxon ID', null=True)),
                ('description', models.TextField(blank=True)),
                ('conservation_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bird Species',
                'ordering': ['common_name_de'],
            },
        ),
        migrations.CreateModel(
            name='BirdDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confidence', models.FloatField(help_text='Confidence Score 0-1')),
                ('top_predictions', models.JSONField(default=list, help_text='Top 5 Predictions mit Scores')),
                ('processed', models.BooleanField(default=False)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.photo')),
                ('pir_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.pirevent')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.video')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.birdspecies')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='species_bir_timesta_f826f8_idx'), models.Index(fields=['species', '-timestamp'], name='species_bir_species_3455f8_idx'), models.Index(fields=['confidence'], name='species_bir_confide_73b064_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('total_confidence', models.FloatField(default=0)),
                ('avg_confidence', models.FloatField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.birdspecies')),
            ],
            options={
                'ordering': ['-date', '-visit_count'],
                'indexes': [models.Index(fields=['-date', 'species'], name='species_dai_date_781506_idx')],
                'unique_together': {('date', 'species')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('visit_count', models.IntegerField(default=0)),
                ('unique_days', models.IntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.birdspecies')),
            ],
            options={
                'ordering': ['-year', '-month', '-visit_count'],
                'indexes': [models.Index(fields=['-year', '-month', 'species'], name='species_mon_year_33a554_idx')],
                'unique_together': {('year', 'month', 'species')},
            },
        ),
        migrations.CreateModel(
            name='YearlyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('unique_months', models.IntegerField(default=0)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.birdspecies')),
            ],
            options={
                'ordering': ['-year', '-visit_count'],
                'indexes': [models.Index(fields=['-year', 'species'], name='species_yea_year_af0a50_idx')],
                'unique_together': {('year', 'species')},
            },
        ),
    ]
