# Generated by Django 5.0.1 on 2026-03-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
        ('sensors', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birddetection',
            name='is_new_visit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='birddetection',
            index=models.Index(fields=['is_new_visit', '-timestamp'], name='species_bir_is_new__54393e_idx'),
        ),
    ]
